### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by explainable-ai** [VanessaAttaFynn/Credit_Scoring_Demo_Project#3]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://vanessaattafynn-credit-scoring-demo-project-app-jqs5bk.streamlitapp.com/vanessaattafynn/credit_scoring_demo_project/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by VanessaAttaFynn** [comment]
Thank you very much for letting me know. I am working on this app.. it is part of a larger app I'm building and it is not complete. I deployed it to test some parts of it so when I am done I will put it back up again.
